services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?schema=public
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # ONLY IN DEV
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
